version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    networks:
      - app-network
  db:
    image: mongo:latest
    container_name: db
    volumes:     
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: 