apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "scaffoldhelm.fullname" . }}-{{
    .Values.deployConfigs.namespace}}'
  namespace: developer
data:
  APP_TYPE: backend
  APP_NAME: app-test
