apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app.kubernetes.io/name: "app-teste"
    app.kubernetes.io/instance: "app-teste"
  name: "app-teste"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "app-teste"
      app.kubernetes.io/instance: "app-teste"
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "0.0.0.0/0"
      labels:
        app.kubernetes.io/name: "app-teste"
        app.kubernetes.io/instance: "app-teste"
    spec:
      containers:
        - image: "nginx:latest"
          name: "app-teste"
          ports:
            - containerPort: 80
              name: "port-nginx"
              protocol: "TCP"
