apiVersion: v1
kind: Service
metadata:
  name: '{{ include "scaffoldhelm.fullname" . }}-{{ .Values.deployConfigs.namespace }}'
  labels:
    app.kubernetes.io/name: '{{ include "scaffoldhelm.name" . }}'
    helm.sh/chart: '{{ include "scaffoldhelm.chart" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  annotations: {}
spec:
  type: '{{ .Values.service.type }}'
  ports:
  - port: '{{ .Values.service.port }}'
    targetPort: '{{ .Values.service.targetPort }}'
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: '{{ include "scaffoldhelm.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
