{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: '{{ include "scaffoldhelm.fullname" . }}-{{ .Values.deployConfigs.namespace}}-virtual-service'
spec:
  hosts:
  - '{{ .Values.deployConfigs.domainName }}'
  gateways:
  - default/{{ .Values.deployConfigs.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: '{{ include "scaffoldhelm.fullname" . }}-{{ .Values.deployConfigs.namespace}}.svc.cluster.local'
{{- end }}
